### ISSUE TITLE
serve_static_assets is deprecated in Rails 4.2

### ISSUE THREAD

**Issue by pelargir** [heroku/rails_serve_static_assets#11]
Rails.configuration.serve_static_assets has been deprecated in Rails 4.2. This results in the following warning message being printed whenever I deploy to Heroku:

```
DEPRECATION WARNING: The configuration option `config.serve_static_assets` has been renamed to
`config.serve_static_files` to clarify its role (it merely enables serving everything in
the `public` folder and is unrelated to the asset pipeline). The `serve_static_assets` alias
will be removed in Rails 5.0. Please migrate your configuration files accordingly.
```

**Comment by dayanthan** [comment]
rails 4.2 already have
config.serve_static_files = ENV['RAILS_SERVE_STATIC_FILES'].present?

so removed the line in production.rb
config.serve_static_assets = true .

it will help you.
