### ISSUE TITLE
Reduce gem size

### ISSUE THREAD

**Issue by colszowka** [heroku/rails_serve_static_assets#13]
The gem weighs in at 25 megabytes, 99.9% of which is the rails app in the test directory. This makes it the biggest gem in my rails app and is a lot of weight to carry around. 

I would suggest to remove the test directory from the gem builds. I'm not sure what the current policy regarding including tests inside gems is. The default `bundle gem` setup does include them, and I think there used to be a way to run tests for rubygems locally, but I'm not sure if people use this at all now that we have travis ci and all, and especially in this case of simple configuration glue, I think the tradeoff is too large.

**Comment by schneems** [comment]
You're talking about download size when using the git version of this gem? We should clean it up. Also you should switch to using the version on rubygems.

**Comment by colszowka** [comment]
@schneems No, the actual gem version on rubygems.org. I bumped into this while reviewing my production `vendor/bundle` directory. Check out `bundle open rails_serve_static_assets` and the gemspec, which includes all files in releases via git ls-files. On v0.0.3.

**Comment by schneems** [comment]
Brutal. I don't know why this isn't working:

```
  gem.test_files    = `git ls-files -- {test,spec,features}/*`.split("\n")
```

The gemspec should be removing any files in the test directory.

**Comment by colszowka** [comment]
Yes :) Actually, the download size is "just" 1.8 mb thanks to gzip, but still :) Also note the size jumped up between [0.0.2 and 0.0.3](https://rubygems.org/gems/rails_serve_static_assets)

I think the `test_files` command is only meant for declaring unit tests for running them locally through rubygems. I think to omit the test dir from the gem package, it must be removed from `gem.files`

**Comment by schneems** [comment]
I've been living a lie, you are correct http://stackoverflow.com/questions/18871541/what-is-the-purpose-of-test-files-configuration-in-a-gemspec.

Turns out the only reason my other gems don't have this problem is because i messed this .gitignore up.

How did you find this, do you regularly run `du` on your gem directory?

**Comment by colszowka** [comment]
Ah yes, exactly. Somewhere in the back of my head this information was still stored away, thanks for digging it out :)

I don't always run `du` on my gem dir, but happened to do it today in an effort to find low-hanging fruit for getting my docker build size down :)

**Comment by schneems** [comment]
I did a git filter branch to force remove the log files and I updated the `.gitignore`. We'll wait for travis to do another test run and i'll cut 0.0.4. Thanks for reporting this! I'm thinking rubygems should warn authors of gem size drastically increasing and it would be nice if that metadata was also shown on the gem's homepage. A few 25mb slip ups will really hurt disk size over time, stuff like this should be hard to accidentally do.

**Comment by colszowka** [comment]
Great, thanks! Actually rubygems shows the rubygem size, check out [the versions list](https://rubygems.org/gems/rails_serve_static_assets). I'd assume it'd be hard to get the rubygem releases API to handle this kind of warning/push mechanism without breaking backwards compatibility, but maybe the bundler gem release tasks could have this as part of a preflight check after building the package.

**Comment by elia** [comment]
couldn't resist 

![most interesting du](http://cdn.meme.am/instances/500x/58596967.jpg)

**Comment by colszowka** [comment]
:arrow_up_small:  `bundle show --paths | xargs -L 1 du -s | sort -n -r | head -n 20`

**Comment by elia** [comment]
:open_mouth:

35M	/Users/elia/.rvm/gems/ruby-2.2.0/gems/web-console-2.0.0

**Comment by colszowka** [comment]
Maybe it's time for another issue filed :)

**Comment by schneems** [comment]
0.0.4 is out with the file reduction. Funny enough. It didn't change the compressed size hardly at all. I double checked and it's 1.5mb on disk after install instead of 25mb. 

re: my comment on sizes in rubygems. It doesn't do much good to show compressed size. It would be nice on push if it unpacked the gem, got the total size and then sent me an email if the size goes up between versions on changes above 25%.

Thanks again for the issue.

**Comment by colszowka** [comment]
@schneems Thanks :) I think the reason it' still over a meg is that on v0.0.2 there was either no test directory or no rails app to test against. I would suggest to just ignore the whole test directory for the gem build since it's ~2mb :)
