### ISSUE TITLE
Deprecation warning: serve_static_assets in configuration

### ISSUE THREAD

**Issue by CJBrew** [heroku/rails_serve_static_assets#14]
https://github.com/heroku/rails_12factor/issues/18

**Comment by schneems** [comment]
Update to 0.0.3 of `rails_serve_static_assets`

**Comment by schneems** [comment]
Update to 0.0.3 of `rails_serve_static_assets`

**Comment by CJBrew** [comment]
I've just seen this https://github.com/heroku/rails_serve_static_assets/blob/master/lib/rails_serve_static_assets/railtie.rb

I'll try the update, thanks
