### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by mojobiri** [heroku/rails_serve_static_assets#15]
There is a deprecation warning in Rails 4.2.1:

DEPRECATION WARNING: The configuration option `config.serve_static_assets` has been renamed to `config.serve_static_files` to clarify its role (it merely enables serving everything in the `public` folder and is unrelated to the asset pipeline). The `serve_static_assets` alias will be removed in Rails 5.0. Please migrate your configuration files accordingly. (called from block in tsort_each at /app/vendor/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226)

So probably
::Rails.configuration.serve_static_assets = true
should be
::Rails.configuration.serve_static_files = true

**Comment by schneems** [comment]
https://github.com/heroku/rails_serve_static_assets/blob/5722be10da67ee94ab852ed72abea1628c05242c/lib/rails_serve_static_assets/railtie.rb#L4-L9

**Comment by schneems** [comment]
Install https://rubygems.org/gems/rails_serve_static_assets/versions/0.0.4
