### ISSUE TITLE
Access protection for assets

### ISSUE THREAD

**Issue by jekuno** [heroku/rails_serve_static_assets#18]
Using this gem sets `config.serve_static_files = true`.
Is there a way to add basic Rack Authentication for files (e.g. assets) which reside in the `/public` directory and are being served by Rails? I need this to provide basic authentication for assets of an Rails 4.2 app running on Heroku.

**Comment by schneems** [comment]
You can set headers in Rails 5 https://github.com/rails/rails/commit/52260581638406d910e09e8d2e66b51acb76c5c6

Otherwise you would need to add your own middleware that checked for basic auth before ActionDispatch::Static
